In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\ANKIT JHA\\Desktop\\HR_comma_sep.csv")

In [3]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years Department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14994                      0    support     low  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  

[14999 rows x 10 columns]

In [4]:
df.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

In [5]:
df.head(3)

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium

In [6]:
df.describe()

satisfaction_level  last_evaluation  number_project  \
count        14999.000000     14999.000000    14999.000000   
mean             0.612834         0.716102        3.803054   
std              0.248631         0.171169        1.232592   
min              0.090000         0.360000        2.000000   
25%              0.440000         0.560000        3.000000   
50%              0.640000         0.720000        4.000000   
75%              0.820000         0.870000        5.000000   
max              1.000000         1.000000        7.000000   

       average_montly_hours  time_spend_company  Work_accident          left  \
count          14999.000000        14999.000000   14999.000000  14999.000000   
mean             201.050337            3.498233       0.144610      0.238083   
std               49.943099            1.460136       0.351719      0.425924   
min               96.000000            2.000000       0.000000      0.000000   
25%              156.000000            3.000000       0.000000      0.000000   
50%              200.000000            3.000000       0.000000      0.000000   
75%              245.000000            4.000000       0.000000      0.000000   
max              310.000000           10.000000       1.000000      1.000000   

       promotion_last_5years  
count           14999.000000  
mean                0.021268  
std                 0.144281  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 0.000000  
max                 1.000000

In [7]:
df = pd.read_csv("C:\\Users\\ANKIT JHA\\Desktop\\HR_comma_sep.csv" , usecols = [0,2,4,5,6,7,9])
df

satisfaction_level  number_project  time_spend_company  Work_accident  \
0                    0.38               2                   3              0   
1                    0.80               5                   6              0   
2                    0.11               7                   4              0   
3                    0.72               5                   5              0   
4                    0.37               2                   3              0   
...                   ...             ...                 ...            ...   
14994                0.40               2                   3              0   
14995                0.37               2                   3              0   
14996                0.37               2                   3              0   
14997                0.11               6                   4              0   
14998                0.37               2                   3              0   

       left  promotion_last_5years  salary  
0         1                      0     low  
1         1                      0  medium  
2         1                      0  medium  
3         1                      0     low  
4         1                      0     low  
...     ...                    ...     ...  
14994     1                      0     low  
14995     1                      0     low  
14996     1                      0     low  
14997     1                      0     low  
14998     1                      0     low  

[14999 rows x 7 columns]

In [8]:
df.head(59)

satisfaction_level  number_project  time_spend_company  Work_accident  \
0                 0.38               2                   3              0   
1                 0.80               5                   6              0   
2                 0.11               7                   4              0   
3                 0.72               5                   5              0   
4                 0.37               2                   3              0   
5                 0.41               2                   3              0   
6                 0.10               6                   4              0   
7                 0.92               5                   5              0   
8                 0.89               5                   5              0   
9                 0.42               2                   3              0   
10                0.45               2                   3              0   
11                0.11               6                   4              0   
12                0.84               4                   5              0   
13                0.41               2                   3              0   
14                0.36               2                   3              0   
15                0.38               2                   3              0   
16                0.45               2                   3              0   
17                0.78               4                   6              0   
18                0.45               2                   3              1   
19                0.76               5                   5              0   
20                0.11               6                   4              0   
21                0.38               2                   3              0   
22                0.09               6                   4              0   
23                0.46               2                   3              0   
24                0.40               2                   3              0   
25                0.89               5                   5              0   
26                0.82               4                   5              0   
27                0.40               2                   3              0   
28                0.41               2                   3              0   
29                0.38               2                   3              0   
30                0.09               6                   4              0   
31                0.45               2                   3              0   
32                0.40               2                   3              0   
33                0.45               2                   3              0   
34                0.84               4                   6              0   
35                0.10               6                   4              0   
36                0.38               2                   3              0   
37                0.45               2                   3              0   
38                0.11               6                   4              0   
39                0.41               2                   3              0   
40                0.87               5                   5              0   
41                0.45               2                   3              0   
42                0.40               2                   3              0   
43                0.10               7                   4              0   
44                0.09               6                   4              0   
45                0.84               3                   4              0   
46                0.40               2                   3              0   
47                0.57               3                   6              0   
48                0.40               2                   3              0   
49                0.43               2                   3              0   
50                0.13               6                   2              0   


In [9]:
dummies = pd.get_dummies(df.salary)
dummies

high  low  medium
0         0    1       0
1         0    0       1
2         0    0       1
3         0    1       0
4         0    1       0
...     ...  ...     ...
14994     0    1       0
14995     0    1       0
14996     0    1       0
14997     0    1       0
14998     0    1       0

[14999 rows x 3 columns]

In [10]:
df1 = pd.concat([df,dummies],axis = 'columns')
df1

satisfaction_level  number_project  time_spend_company  Work_accident  \
0                    0.38               2                   3              0   
1                    0.80               5                   6              0   
2                    0.11               7                   4              0   
3                    0.72               5                   5              0   
4                    0.37               2                   3              0   
...                   ...             ...                 ...            ...   
14994                0.40               2                   3              0   
14995                0.37               2                   3              0   
14996                0.37               2                   3              0   
14997                0.11               6                   4              0   
14998                0.37               2                   3              0   

       left  promotion_last_5years  salary  high  low  medium  
0         1                      0     low     0    1       0  
1         1                      0  medium     0    0       1  
2         1                      0  medium     0    0       1  
3         1                      0     low     0    1       0  
4         1                      0     low     0    1       0  
...     ...                    ...     ...   ...  ...     ...  
14994     1                      0     low     0    1       0  
14995     1                      0     low     0    1       0  
14996     1                      0     low     0    1       0  
14997     1                      0     low     0    1       0  
14998     1                      0     low     0    1       0  

[14999 rows x 10 columns]

In [11]:
df2 = df1.drop(['salary','high','left'],axis = 'columns')
df2

satisfaction_level  number_project  time_spend_company  Work_accident  \
0                    0.38               2                   3              0   
1                    0.80               5                   6              0   
2                    0.11               7                   4              0   
3                    0.72               5                   5              0   
4                    0.37               2                   3              0   
...                   ...             ...                 ...            ...   
14994                0.40               2                   3              0   
14995                0.37               2                   3              0   
14996                0.37               2                   3              0   
14997                0.11               6                   4              0   
14998                0.37               2                   3              0   

       promotion_last_5years  low  medium  
0                          0    1       0  
1                          0    0       1  
2                          0    0       1  
3                          0    1       0  
4                          0    1       0  
...                      ...  ...     ...  
14994                      0    1       0  
14995                      0    1       0  
14996                      0    1       0  
14997                      0    1       0  
14998                      0    1       0  

[14999 rows x 7 columns]

In [12]:
y = df1['left']
y

0        1
1        1
2        1
3        1
4        1
        ..
14994    1
14995    1
14996    1
14997    1
14998    1
Name: left, Length: 14999, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(df2,y,test_size = 0.2)

In [15]:
from sklearn.linear_model import LogisticRegression
model =LogisticRegression()

In [16]:
model.fit(X_train,y_train)

C:\Users\ANKIT JHA\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
model.score(X_test,y_test)

0.8013333333333333

In [18]:
model.predict([[0.59,3,5,1,1,1,1]])

array([0], dtype=int64)

In [19]:
model.predict([[0.80,2,8,2,2,0,1]])

array([0], dtype=int64)

In [20]:
model.predict([[0.80,5,6,0,0,0,1]])

array([0], dtype=int64)

In [21]:
model.predict([[0.09,2,2,0,0,1,0]])

array([1], dtype=int64)

In [22]:
model.predict([[0.23,2,3,0,0,1,0]])

array([1], dtype=int64)

In [23]:
model.predict([[0.33,2,3,0,0,1,0]])

array([1], dtype=int64)

In [24]:
model.predict([[0.53,2,3,0,0,1,0]])

array([0], dtype=int64)

In [33]:
model.predict([[0.30,1,8,1,0,1,0]])

array([1], dtype=int64)

In [25]:
df.head()

satisfaction_level  number_project  time_spend_company  Work_accident  \
0                0.38               2                   3              0   
1                0.80               5                   6              0   
2                0.11               7                   4              0   
3                0.72               5                   5              0   
4                0.37               2                   3              0   

   left  promotion_last_5years  salary  
0     1                      0     low  
1     1                      0  medium  
2     1                      0  medium  
3     1                      0     low  
4     1                      0     low